name: Blob storage website CI

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
            az account set --subscription "Visual Studio Enterprise with MSDN"
            az storage blob upload-batch --account-name storagealphaphotography  --auth-mode key -d '$web' -s .
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "cdnprofilealphaphotographyweb" --name "cdnendpointalphaphotographyweb " --resource-group "Default-ActivityLogAlerts"
    # Azure logout
    - name: logout
      run: |
            az logout
      if: always()       
